backend:
  name: git-gateway
  branch: master

media_folder: admin/img
public_folder: /img

collections:
    - name: "pages"
    label: "Pages"
    files:
      - file: "/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          